# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'TESTSPN'
    subscriptionId: 'a891bc5a-8db2-4787-acd7-7016fd853d23'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'TESTRG_V'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/vamsichalla18/ARMTemplate/blob/main/azuredeploy.json'
    csmParametersFileLink: 'https://github.com/vamsichalla18/ARMTemplate/blob/main/azuredeploy.parameters.dev.json'
    deploymentMode: 'Incremental'
    deploymentName: 'devops'
